services:
  - type: web
    name: lead-generation-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install
      python -m playwright install-deps
    startCommand: bash run.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PORT
        value: 10000
    plan: free
